import { Product, BlogPost, Testimonial } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'FloraVita Probiyotik Plus',
    slug: 'floravita-probiyotik-plus',
    description: '10 farklı probiyotik suş içeren güçlü bağırsak desteği',
    longDesc: 'FloraVita Probiyotik Plus, 10 milyar CFU ile bağırsak floranızı dengeler. Sindirim sisteminizi güçlendirir, bağışıklığınızı destekler.',
    price: 299.90,
    oldPrice: 399.90,
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80'],
    category: 'Probiyotik',
    stock: 50,
    featured: true,
    rating: 4.8,
    reviewCount: 124,
    ingredients: ['Lactobacillus acidophilus', 'Bifidobacterium longum', 'Lactobacillus rhamnosus', 'İnülin'],
    benefits: ['Sindirim sağlığı', 'Bağışıklık güçlendirme', 'Şişkinlik azaltma'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'FloraVita Prebiyotik Lif',
    slug: 'floravita-prebiyotik-lif',
    description: 'Bağırsak bakterilerinizi besleyen doğal prebiyotik lif formülü',
    longDesc: 'Akasya lifi, inülin ve psyllium husk karışımından oluşan prebiyotik formülümüz, iyi bakterilerinizi besler ve bağırsak hareketlerini düzenler.',
    price: 189.90,
    oldPrice: 229.90,
    images: ['https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&q=80'],
    category: 'Prebiyotik',
    stock: 35,
    featured: true,
    rating: 4.6,
    reviewCount: 89,
    ingredients: ['Akasya Lifi', 'İnülin', 'Psyllium Husk', 'Feniks Çiçeği Özü'],
    benefits: ['Düzenli bağırsak hareketi', 'Kolesterol desteği', 'Kan şekeri dengesi'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'FloraVita Sindirim Enzimi',
    slug: 'floravita-sindirim-enzimi',
    description: 'Yemek sonrası şişkinlik ve gaz problemlerine doğal çözüm',
    longDesc: 'Bitkisel kaynaklı sindirim enzimleri; protein, yağ ve karbonhidratların sindirimini kolaylaştırır.',
    price: 249.90,
    images: ['https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&q=80'],
    category: 'Sindirim',
    stock: 45,
    featured: true,
    rating: 4.7,
    reviewCount: 67,
    ingredients: ['Amilaz', 'Lipaz', 'Protaz', 'Bromelain', 'Papain'],
    benefits: ['Hızlı sindirim', 'Gaz ve şişkinlik azaltma', 'Besin emilimini artırma'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'FloraVita Gut Reset Paketi',
    slug: 'floravita-gut-reset-paketi',
    description: '30 günlük bağırsak sıfırlama programı — 3 ürün bir arada',
    longDesc: 'Probiyotik Plus, Prebiyotik Lif ve Sindirim Enzimini bir arada sunan 30 günlük Gut Reset Paketi.',
    price: 649.90,
    oldPrice: 839.70,
    images: ['https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80'],
    category: 'Paket',
    stock: 20,
    featured: true,
    rating: 4.9,
    reviewCount: 203,
    ingredients: ['Probiyotik Plus', 'Prebiyotik Lif', 'Sindirim Enzimi'],
    benefits: ['Tam bağırsak desteği', '%23 tasarruf', '30 günlük program'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'FloraVita Aloe Vera Jel',
    slug: 'floravita-aloe-vera-jel',
    description: 'İç bağırsak duvarını onaran ve yatıştıran saf aloe vera',
    longDesc: 'Organik aloe vera jeli, bağırsak mukoza tabakasını korur ve yeniler.',
    price: 159.90,
    images: ['https://images.unsplash.com/photo-1600857544200-b2f466c28776?w=600&q=80'],
    category: 'Bitkisel',
    stock: 60,
    featured: false,
    rating: 4.5,
    reviewCount: 41,
    ingredients: ['Organik Aloe Vera', 'Vitamin C', 'Vitamin E'],
    benefits: ['Bağırsak duvarı onarımı', 'Anti-inflamatuar', 'Detoks desteği'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'FloraVita Zencefil & Zerdeçal',
    slug: 'floravita-zencefil-zerdecal-kapsul',
    description: 'Anti-inflamatuar güç ikilisi — bağırsak iltihabına karşı',
    longDesc: 'Zencefil ve zerdeçalın birleşimi bağırsak iltihaplanmasını azaltır.',
    price: 219.90,
    oldPrice: 259.90,
    images: ['https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&q=80'],
    category: 'Bitkisel',
    stock: 40,
    featured: false,
    rating: 4.6,
    reviewCount: 55,
    ingredients: ['Zencefil Özü', 'Zerdeçal (Kurkumin)', 'Biyoperin', 'Zeytinyağı'],
    benefits: ['Anti-inflamatuar', 'Sindirim rahatlığı', 'Bağışıklık desteği'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Bağırsak Sağlığı Neden Bu Kadar Önemli?',
    slug: 'bagirsak-sagligi-neden-onemli',
    excerpt: 'Bağırsaklarımız "ikinci beyin" olarak anılır. Peki bu ne anlama geliyor ve neden bu kadar önemli?',
    coverImage: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&q=80',
    category: 'Sağlık',
    tags: ['bağırsak sağlığı', 'mikrobiyota', 'sağlık'],
    author: 'FloraVita Uzmanlar Ekibi',
    readTime: 5,
    publishedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    title: 'Probiyotik mi, Prebiyotik mi? Fark Nedir?',
    slug: 'probiyotik-prebiyotik-fark',
    excerpt: 'Probiyotik ve prebiyotik kavramları çok karıştırılır. Gerçekte ne anlama gelirler ve nasıl seçilir?',
    coverImage: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800&q=80',
    category: 'Bilgi',
    tags: ['probiyotik', 'prebiyotik', 'sağlık', 'takviye'],
    author: 'FloraVita Uzmanlar Ekibi',
    readTime: 4,
    publishedAt: '2024-01-20T00:00:00Z',
  },
  {
    id: '3',
    title: '7 Günde Bağırsak Sağlığı Programı',
    slug: '7-gunde-bagirsak-sagligi-programi',
    excerpt: 'Bir hafta gibi kısa sürede bağırsaklarınızı nasıl sıfırlayabilirsiniz? Adım adım program.',
    coverImage: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80',
    category: 'Program',
    tags: ['detoks', 'program', 'bağırsak', 'sağlık'],
    author: 'FloraVita Uzmanlar Ekibi',
    readTime: 6,
    publishedAt: '2024-01-25T00:00:00Z',
  },
  {
    id: '4',
    title: 'Şişkinlik ve Gaz Problemlerinin 5 Temel Nedeni',
    slug: 'siskinlik-gaz-problemleri-nedenleri',
    excerpt: 'Yemekten sonra karnınız sıkça şişiyor mu? İşte gizli nedenler ve çözüm yolları...',
    coverImage: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    category: 'Sağlık',
    tags: ['şişkinlik', 'gaz', 'sindirim', 'bağırsak'],
    author: 'FloraVita Uzmanlar Ekibi',
    readTime: 5,
    publishedAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '5',
    title: 'Fermente Gıdaların Bağırsak Sağlığına Etkileri',
    slug: 'fermente-gidalarin-bagirsak-sagligina-etkileri',
    excerpt: 'Kefir, yoğurt, kimchi... Fermente gıdalar neden bu kadar güçlü ve bağırsak floranızı nasıl etkiler?',
    coverImage: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80',
    category: 'Beslenme',
    tags: ['fermente', 'kefir', 'yoğurt', 'probiyotik'],
    author: 'FloraVita Uzmanlar Ekibi',
    readTime: 4,
    publishedAt: '2024-02-10T00:00:00Z',
  },
  {
    id: '6',
    title: 'Stres ve Bağırsak Sağlığı Arasındaki Gizli Bağlantı',
    slug: 'stres-bagirsak-baglantisi',
    excerpt: 'Stresli olduğunuzda mideniz neden bozuluyor? Bağırsak-beyin ekseni bilim tarafından yanıtlanıyor.',
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    category: 'Sağlık',
    tags: ['stres', 'bağırsak', 'beyin', 'sağlık'],
    author: 'FloraVita Uzmanlar Ekibi',
    readTime: 5,
    publishedAt: '2024-02-15T00:00:00Z',
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Ayşe K.',
    location: 'İstanbul',
    rating: 5,
    comment: '3 aydır FloraVita Probiyotik Plus kullanıyorum. Şişkinlik sorunum tamamen geçti, enerjim arttı. Kesinlikle tavsiye ederim!',
    product: 'FloraVita Probiyotik Plus',
    verified: true,
    createdAt: '2024-01-10T00:00:00Z',
  },
  {
    id: '2',
    name: 'Mehmet T.',
    location: 'Ankara',
    rating: 5,
    comment: 'Gut Reset Paketi hayatımı değiştirdi. 2 haftada farkı hissettim. Uyku düzenim de düzeldi, inanılmaz!',
    product: 'FloraVita Gut Reset Paketi',
    verified: true,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '3',
    name: 'Fatma S.',
    location: 'İzmir',
    rating: 5,
    comment: 'Uzun süredir IBS sorunu yaşıyordum. Doktorumun önerisiyle FloraVita kullanmaya başladım. Çok memnunum.',
    product: 'FloraVita Sindirim Enzimi',
    verified: true,
    createdAt: '2024-01-20T00:00:00Z',
  },
  {
    id: '4',
    name: 'Ali R.',
    location: 'Bursa',
    rating: 4,
    comment: 'Prebiyotik Lif gerçekten çok etkili. İlk hafta biraz gaz yaptı ama sonra harika hissettim.',
    product: 'FloraVita Prebiyotik Lif',
    verified: true,
    createdAt: '2024-01-25T00:00:00Z',
  },
  {
    id: '5',
    name: 'Zeynep A.',
    location: 'Antalya',
    rating: 5,
    comment: 'Kargo çok hızlı geldi, ürün kaliteli ambalajda. Aloe Vera Jeli çok beğeniyorum, hafif ve etkili.',
    product: 'FloraVita Aloe Vera Jel',
    verified: true,
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Burak D.',
    location: 'Adana',
    rating: 5,
    comment: 'Yıllardır devam eden reflü problemim ciddi anlamda azaldı. FloraVita ekibine teşekkürler!',
    product: 'FloraVita Gut Reset Paketi',
    verified: true,
    createdAt: '2024-02-05T00:00:00Z',
  },
];
